TARGETS = contrib

all: $(TARGETS)

clean:

distclean: clean

contrib:

install:
	mkdir -p ${INSTALL_ROOT}${PREFIX}/share/doc/mythtv-backend/contrib/
	cp -r * ${INSTALL_ROOT}${PREFIX}/share/doc/mythtv-backend/contrib/
	rm ${INSTALL_ROOT}${PREFIX}/share/doc/mythtv-backend/contrib/Makefile

clean:

uninstall:
	rm -rf ${INSTALL_ROOT}${PREFIX}/share/doc/mythtv-backend/contrib

